---
- hosts: target1
  remote_user: ec2-user
  become: yes
  gather_facts: no
  connection: ssh
  tasks:
    - name: Group for "Jamie"
      group:
        name: Jamie
        state: present
    - name: Add user "Jamie" to remote server
      user:
       name: Jamie
       group: Jamie
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa
    - name: folder1
      file:
        path: /opt/folder1
        state: directory
        owner: Jamie
        group: Jamie
        mode: '0700'
    - name: folder2
      file:
        path: /opt/folder2
        state: directory
        owner: Jamie
        mode: '0700'
    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
    - name: install nginx
      command: amazon-linux-extras install nginx1 -y
    - name: "create www directory"
      file:
        path: /var/www/emredemo.com
        state: directory
        mode: '0775'
        owner: ec2-user
        group: ec2-user
    - name: copy nginx site.conf
      template:
        src: site.conf
        dest: /etc/nginx/conf.d/
        owner: root
        group: root
        mode: '0644'
    - name: restart nginx on failure
      blockinfile:
        path: "/usr/lib/systemd/system/nginx.service"
        insertbefore: "Type=forking"
        block: |
             Restart=on-failure
             RestartSec=5s
    - name: enable service nginx and reload
      systemd:
        name: nginx
        state: started
        enabled: yes
        daemon_reload: yes
