version: "3.7"
services:

  flask:
    build: flask
    restart: always
    container_name: flask_app
    image: flask_app:v1.0
    networks: 
      - app

  nginx:
    build: nginx
    restart: always
    container_name: nginx_proxy
    image: nginx_proxy:v1.0
    networks: 
      - app
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - FLASK_HOST=flask
      - FLASK_PORT=5000 

networks: 
  app:
    name: demo-network
